### ISSUE TITLE
{Feature request} Cooldown between each /tpvp

### ISSUE THREAD

**Issue by v4rl1** [ProjectsForAll/Pacifism#1]
Hello,
I have a small feature request is the ability to add a cooldown between each times a user can type /tpvp to prevent users from changing it very quickly. I'm guessing the difficulty would be to make it so the cooldown also lasts if they try to log off and on.

Thank you very much for the great plugin you made and thanks for considering my request.

**Comment by DrakDv** [comment]
I can do this.

**Comment by DrakDv** [comment]
https://github.com/ProjectsForAll/Pacifism/commit/e44baf71e1d62b466da35df2ddcde19fd0937398

Added.

Check it out here: https://modrinth.com/plugin/pacifism/versions
