### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jbax1899** [ProjectsForAll/Pacifism#5]
After adding this plugin, memory usage continued to climb until it ran out. A Spark profile also revealed an abnormally high CPU usage, about 5%. Removing it fixed the issue.

Game version: 1.20.6 (Paper)
Java: 21

**Comment by DrakDv** [comment]
Looking into this now.

**Comment by DrakDv** [comment]
This has been fixed.

**Comment by jbax1899** [comment]
Can confirm this fix worked. Thank you!
